import { useQuery } from '@tanstack/react-query'
import { api } from '../api'
import { ErrorState, Icon, Skeleton } from '../components/ui'
import { formatDate, listFrom, PageHeading } from '../components/page'
import type { AuditEntry, Device, Paged, Stats } from '../types'

const statConfig = [{key:'documents',label:'Документи',icon:'documents' as const},{key:'categories',label:'Категории',icon:'categories' as const},{key:'devices',label:'Свързани устройства',icon:'devices' as const},{key:'users',label:'Потребители',icon:'users' as const}]
export function DashboardPage() { const stats = useQuery({queryKey:['stats'],queryFn:()=>api<Stats>('/api/stats'),retry:false}); const devices = useQuery({queryKey:['devices'],queryFn:()=>api<Device[]|Paged<Device>>('/api/devices'),retry:false}); const audit = useQuery({queryKey:['audit','recent'],queryFn:()=>api<AuditEntry[]|Paged<AuditEntry>>('/api/audit?page=1'),retry:false}); return <section className="page"><PageHeading title="Добре дошли" text="Ето какво се случва в системата за киоски."/>{stats.isError ? <ErrorState onRetry={()=>stats.refetch()}/> : <div className="stat-grid">{statConfig.map(item=><article className="card stat-card" key={item.key}><div className="stat-card__icon"><Icon name={item.icon}/></div>{stats.isLoading?<><Skeleton/><Skeleton className="skeleton-text"/></>:<><strong className="stat-card__value">{stats.data?.[item.key] ?? 0}</strong><span className="stat-card__label">{item.label}</span></>}</article>)}</div>}<div className="content-grid"><section className="card"><header className="card__header"><h2>Устройства</h2><span className="text-muted">Последна активност</span></header>{devices.isLoading ? <LoadingRows/> : devices.isError ? <ErrorState onRetry={()=>devices.refetch()}/> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Устройство</th><th>Последно видяно</th><th>Версия</th></tr></thead><tbody>{listFrom(devices.data).slice(0,5).map(device=><tr key={device.id}><td><strong>{device.name || device.label || device.id}</strong><br/><span className="mono text-muted">{device.id}</span></td><td>{device.lastSeenAt ? <span className="text-ok"><span className="badge-dot"/> {formatDate(device.lastSeenAt)}</span> : <span className="text-muted">Няма данни</span>}</td><td>{device.appVersion || '—'}</td></tr>)}</tbody></table>{!listFrom(devices.data).length&&<div className="empty-state"><Icon name="devices" size={36}/><h3>Няма свързани устройства</h3><p>Създайте ключ за първото устройство от раздел „Устройства“.</p></div>}</div>}</section><section className="card"><header className="card__header"><h2>Последни действия</h2></header>{audit.isLoading?<LoadingRows/>:audit.isError?<ErrorState onRetry={()=>audit.refetch()}/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Действие</th><th>Кога</th></tr></thead><tbody>{listFrom(audit.data).slice(0,5).map(entry=><tr key={entry.id}><td><strong>{entry.summary}</strong><br/><span className="text-muted">{entry.actorName || entry.actorType}</span></td><td className="text-muted">{formatDate(entry.at)}</td></tr>)}</tbody></table>{!listFrom(audit.data).length&&<div className="empty-state"><Icon name="audit" size={36}/><h3>Няма записи</h3><p>Действията в системата ще се появят тук.</p></div>}</div>}</section></div></section> }
function LoadingRows(){return <div className="loading-lines"><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div>}
