import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api'
import { Button, ConfirmDialog, EmptyState, ErrorState, Icon, Modal, useToast } from '../components/ui'
import { formatDate, listFrom, PageHeading } from '../components/page'
import type { ApiError, Paged, Role, User } from '../types'
type UserForm={name:string;email:string;role:Role;password:string}
const blank:UserForm={name:'',email:'',role:'viewer',password:''}
export function UsersPage(){const client=useQueryClient();const {toast}=useToast();const users=useQuery({queryKey:['users'],queryFn:()=>api<User[]|Paged<User>>('/api/users'),retry:false});const [editor,setEditor]=useState<User|null|'new'>(null);const [remove,setRemove]=useState<User|null>(null);const invalidate=()=>client.invalidateQueries({queryKey:['users']});const save=useMutation({mutationFn:({item,form}:{item:User|null|'new';form:UserForm})=>{const {password,...data}=form;return item==='new'?api<User>('/api/users',{method:'POST',body:JSON.stringify(form)}):api<User>(`/api/users/${item!.id}`,{method:'PATCH',body:JSON.stringify(password?form:data)})},onSuccess:()=>{invalidate();setEditor(null);toast('Потребителят е запазен.')},onError:(e:ApiError)=>toast(e.message,'error')});const del=useMutation({mutationFn:(id:string)=>api(`/api/users/${id}`,{method:'DELETE'}),onSuccess:()=>{invalidate();setRemove(null);toast('Потребителят е изтрит.')},onError:(e:ApiError)=>toast(e.message,'error')});const data=listFrom(users.data);return <section className="page"><PageHeading title="Потребители" text="Управлявайте достъпа до административната платформа." action={<Button onClick={()=>setEditor('new')}><Icon name="plus"/> Нов потребител</Button>}/><section className="card">{users.isLoading?<div className="loading-lines"><span className="skeleton"/><span className="skeleton"/></div>:users.isError?<ErrorState onRetry={()=>users.refetch()}/>:data.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Име</th><th>Имейл</th><th>Роля</th><th>Създаден</th><th/></tr></thead><tbody>{data.map(user=><tr key={user.id}><td><strong>{user.name}</strong></td><td>{user.email}</td><td><RoleBadge role={user.role}/></td><td>{formatDate(user.createdAt,false)}</td><td><div className="actions"><button className="icon-button" aria-label={`Редактирай ${user.name}`} onClick={()=>setEditor(user)}><Icon name="edit"/></button><button className="icon-button text-danger" aria-label={`Изтрий ${user.name}`} onClick={()=>setRemove(user)}><Icon name="trash"/></button></div></td></tr>)}</tbody></table></div>:<EmptyState icon="users" title="Няма добавени потребители" text="Добавете човек от екипа и задайте подходяща роля." action={<Button onClick={()=>setEditor('new')}><Icon name="plus"/> Нов потребител</Button>}/>}</section>{editor&&<UserModal user={editor==='new'?null:editor} busy={save.isPending} onClose={()=>setEditor(null)} onSave={form=>save.mutate({item:editor,form})}/>} {remove&&<ConfirmDialog title="Изтриване на потребител" message={<>Сигурни ли сте, че искате да изтриете потребителя „{remove.name}“?</>} busy={del.isPending} onClose={()=>setRemove(null)} onConfirm={()=>del.mutate(remove.id)}/>}</section>}
function RoleBadge({role}:{role:Role}){return <span className="badge">{role==='admin'?'Администратор':role==='editor'?'Редактор':'Наблюдател'}</span>}
function UserModal({user,busy,onClose,onSave}:{user:User|null;busy:boolean;onClose:()=>void;onSave:(form:UserForm)=>void}){const [form,setForm]=useState<UserForm>(user?{name:user.name,email:user.email,role:user.role,password:''}:blank);return <Modal title={user?'Редактиране на потребител':'Нов потребител'} onClose={onClose}><form onSubmit={(e:FormEvent)=>{e.preventDefault();onSave(form)}}><div className="modal__body"><div className="form-grid"><div className="field form-grid--full"><label htmlFor="user-name">Име</label><input id="user-name" className="input" value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} required/></div><div className="field form-grid--full"><label htmlFor="user-email">Имейл</label><input id="user-email" type="email" className="input" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} required/></div><div className="field"><label htmlFor="user-role">Роля</label><select id="user-role" className="select" value={form.role} onChange={e=>setForm(v=>({...v,role:e.target.value as Role}))}><option value="admin">Администратор</option><option value="editor">Редактор</option><option value="viewer">Наблюдател</option></select></div><div className="field"><label htmlFor="user-password">{user?'Нова парола (по желание)':'Парола'}</label><input id="user-password" type="password" className="input" value={form.password} onChange={e=>setForm(v=>({...v,password:e.target.value}))} required={!user}/></div></div></div><footer className="modal__footer"><Button variant="secondary" type="button" onClick={onClose}>Отказ</Button><Button type="submit" disabled={busy}>{busy?'Запазване…':'Запази'}</Button></footer></form></Modal>}
