import { apiUrl, authStorage } from '../api'
import type { ApiError } from '../types'

export function isPdf(file: File) { return file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf') }
export function validatePdf(file: File) { if (!isPdf(file)) return 'Файлът не е PDF и не може да бъде качен.'; if (file.size > 100 * 1024 * 1024) return 'Файлът надвишава максималния размер от 100 MB.'; return null }
/** A document can be sent with one file, or with a Bulgarian and an English one together. */
export function uploadPdfs<T>(path: string, files: Record<string, File>, extra: { meta?: unknown; note?: string } = {}, onProgress?: (value:number)=>void) { return uploadPdf<T>(path, undefined, extra, onProgress, files) }

export function uploadPdf<T>(path: string, file?: File, extra: { meta?: unknown; note?: string } = {}, onProgress?: (value:number)=>void, files?: Record<string, File>) { return new Promise<T>((resolve,reject)=>{ const form=new FormData(); if(file) form.append('file',file); if(files) for(const [field,f] of Object.entries(files)) form.append(field,f); if(extra.meta!==undefined) form.append('meta',JSON.stringify(extra.meta)); if(extra.note!==undefined) form.append('note',extra.note); const xhr=new XMLHttpRequest(); xhr.open('POST',apiUrl(path)); const token=authStorage.get(); if(token)xhr.setRequestHeader('Authorization',`Bearer ${token}`); xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(Math.round(e.loaded/e.total*100))}; xhr.onerror=()=>reject({status:0,message:'Няма връзка със сървъра. Опитайте отново по-късно.'} satisfies ApiError); xhr.onload=()=>{const body=xhr.responseText?JSON.parse(xhr.responseText):undefined;if(xhr.status>=200&&xhr.status<300)resolve(body as T);else {if(xhr.status===401){authStorage.clear();window.dispatchEvent(new Event('septona:unauthorized'))}reject({status:xhr.status,code:body?.error?.code,message:body?.error?.message||'Качването не бе успешно.',payload:body} satisfies ApiError)}}; xhr.send(form) }) }
